config/routes.rb
Rails.application.routes.draw do

  root 'drawings#index'
  resources :drawings do
    collection { post :import }
  end

end

app/models/drawing.rb
class Drawing < ActiveRecord::Base

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Drawing.create! row.to_hash
		end
	end

	# def self.search(search)
	# 	if search
	# 		where(["shape LIKE ?","%#{search}%"])
	# 	else
	# 		all
	# 	end
	# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_action :set_drawing, only: [:show, :edit, :update, :destroy]

  # GET /drawings
  # GET /drawings.json
  def index
    # @drawings = Drawing.all
    # @drawings = Drawing.search(params[:search])


    @search = Drawing.search(params[:q])
    @drawings = @search.result
 
  end

  # GET /drawings/1
  # GET /drawings/1.json
  def show
  end

  # GET /drawings/new
  def new
    @drawing = Drawing.new
  end

  # GET /drawings/1/edit
  def edit
  end

  # POST /drawings
  # POST /drawings.json
  def create
    @drawing = Drawing.new(drawing_params)

    respond_to do |format|
      if @drawing.save
        format.html { redirect_to @drawing, notice: 'Drawing was successfully created.' }
        format.json { render :show, status: :created, location: @drawing }
      else
        format.html { render :new }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drawings/1
  # PATCH/PUT /drawings/1.json
  def update
    respond_to do |format|
      if @drawing.update(drawing_params)
        format.html { redirect_to @drawing, notice: 'Drawing was successfully updated.' }
        format.json { render :show, status: :ok, location: @drawing }
      else
        format.html { render :edit }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drawings/1
  # DELETE /drawings/1.json
  def destroy
    @drawing.destroy
    respond_to do |format|
      format.html { redirect_to drawings_url, notice: 'Drawing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def import
    Drawing.import(params[:file])
    redirect_to drawings_path, notice: "Drawings Successfully added"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drawing
      @drawing = Drawing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drawing_params
      params.require(:drawing).permit(:newdrawing, :olddrawing, :year, :description, :width, :length, :shape, :subset, :step, :widthinches, :lengthinches, :brand)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/views/drawings/_form.html.erb
<%= form_for(@drawing) do |f| %>
  <% if @drawing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drawing.errors.count, "error") %> prohibited this drawing from being saved:</h2>

      <ul>
      <% @drawing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :newdrawing %><br>
    <%= f.text_field :newdrawing %>
  </div>
  <div class="field">
    <%= f.label :olddrawing %><br>
    <%= f.text_field :olddrawing %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :shape %><br>
    <%= f.text_field :shape %>
  </div>
  <div class="field">
    <%= f.label :subset %><br>
    <%= f.text_field :subset %>
  </div>
  <div class="field">
    <%= f.label :step %><br>
    <%= f.text_field :step %>
  </div>
  <div class="field">
    <%= f.label :widthinches %><br>
    <%= f.number_field :widthinches %>
  </div>
  <div class="field">
    <%= f.label :lengthinches %><br>
    <%= f.number_field :lengthinches %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drawings/edit.html.erb
<h1>Editing Drawing</h1>

<%= render 'form' %>

<%= link_to 'Show', @drawing %> |
<%= link_to 'Back', drawings_path %>

app/views/drawings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drawing Search</h1>

<%= search_form_for @search do |f| %>
<div class ="field">
  <%= f.label :brand_cont, "Brand contains:" %>
  <%= f.text_field :brand_cont %>
</div>
<div class ="field">
  <%= f.label :shape_cont, "Shape contains:" %>
 <%= f.text_field :shape_cont %>

</div>


<div class ="field">
  <%= f.label :subset_cont, "Subset contains:" %>
  <%= f.text_field :subset_cont %>
</div>
<div class="field">
  <%= f.label :width_gteq, "Width(ft) Between" %>
  <%= f.text_field :width_gteq %>
  <%= f.label :width_lteq, "and" %>
  <%= f.text_field :width_lteq %>
</div>
<div class="field">
  <%= f.label :length_gteq, "Length(ft) Between" %>
  <%= f.text_field :length_gteq %>
  <%= f.label :length_lteq, "and" %>
  <%= f.text_field :length_lteq %>
</div>
<div class ="field">
  <%= f.label :newdrawing_cont, "New Drawing # contains:" %>
  <%= f.text_field :newdrawing_cont %>
</div>
<div class ="field">
  <%= f.label :olddrawing_cont, "Old Drawing # contains:" %>
  <%= f.text_field :olddrawing_cont %>
</div>
<div class ="field">
  <%= f.label :step_cont, "Step(yes/no):" %>
  <%= f.text_field :step_cont %>
</div>
<div class="field">
  <%= f.label :widthinches_gteq, "Width(inches) Between" %>
  <%= f.text_field :widthinches_gteq %>
  <%= f.label :widthinches_lteq, "and" %>
  <%= f.text_field :widthinches_lteq %>
</div>
<div class="field">
  <%= f.label :lengthinches_gteq, "Length(inches) Between" %>
  <%= f.text_field :lengthinches_gteq %>
  <%= f.label :lengthinches_lteq, "and" %>
  <%= f.text_field :lengthinches_lteq %>
</div>
<div class="actions">
  <%= f.submit "Search" %>
</div>

<%= link_to "My PDF", asset_path("16000.pdf") %>

<% end %>


<table>
  <thead>
    <tr>
      <th><%= sort_link @search, :newdrawing, "Newdrawing"%></th>
      <th><%= sort_link @search, :olddrawing, "Olddrawing"%></th>
      <th><%= sort_link @search, :year, "Year"%></th>
      <th><%= sort_link @search, :description, "Description"%></th>
      <th><%= sort_link @search, :width, "Width"%></th>
      <th><%= sort_link @search, :length, "Length"%></th>
      <th><%= sort_link @search, :shape, "Shape"%></th>
      <th><%= sort_link @search, :subset, "Subset"%></th>
      <th><%= sort_link @search, :step, "Step"%></th>
      <th><%= sort_link @search, :widthinches, "Widthinches"%></th>
      <th><%= sort_link @search, :lengthinches, "Lengthinches"%></th>
      <th><%= sort_link @search, :brand, "Brand"%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drawings.each do |drawing| %>
      <tr>
        <td><%= drawing.newdrawing %></td>
        <td><%= drawing.olddrawing %></td>
        <td><%= drawing.year %></td>
        <td><%= drawing.description %></td>
        <td><%= drawing.width %></td>
        <td><%= drawing.length %></td>
        <td><%= drawing.shape %></td>
        <td><%= drawing.subset %></td>
        <td><%= drawing.step %></td>
        <td><%= drawing.widthinches %></td>
        <td><%= drawing.lengthinches %></td>
        <td><%= drawing.brand %></td>
        <td><%= link_to 'Show', drawing %></td>
        <td><%= link_to 'Edit', edit_drawing_path(drawing) %></td>
        <td><%= link_to 'Destroy', drawing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "PDF", asset_path("#{drawing.newdrawing}.pdf") %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3>Import Drawings</h3>
<%= form_tag import_drawings_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Upload Drawings" %>
<% end %>
<br>

<%= link_to 'New Drawing', new_drawing_path %>

app/views/drawings/new.html.erb
<h1>New Drawing</h1>



<%= render 'form' %>

<%= link_to 'Back', drawings_path %>

app/views/drawings/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Newdrawing:</strong>
  <%= @drawing.newdrawing %>
</p>

<p>
  <strong>Olddrawing:</strong>
  <%= @drawing.olddrawing %>
</p>

<p>
  <strong>Year:</strong>
  <%= @drawing.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @drawing.description %>
</p>

<p>
  <strong>Width:</strong>
  <%= @drawing.width %>
</p>

<p>
  <strong>Length:</strong>
  <%= @drawing.length %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @drawing.shape %>
</p>

<p>
  <strong>Subset:</strong>
  <%= @drawing.subset %>
</p>

<p>
  <strong>Step:</strong>
  <%= @drawing.step %>
</p>

<p>
  <strong>Widthinches:</strong>
  <%= @drawing.widthinches %>
</p>

<p>
  <strong>Lengthinches:</strong>
  <%= @drawing.lengthinches %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @drawing.brand %>
</p>

<%= link_to 'Edit', edit_drawing_path(@drawing) %> |
<%= link_to 'Back', drawings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mcewen4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>